ALTER TABLE Papeis ADD COLUMN ver_banners BOOLEAN DEFAULT FALSE;

CREATE TABLE Banners (
    id INT AUTO_INCREMENT PRIMARY KEY,
    foto_url VARCHAR(500) NOT NULL,
    ordem INT NOT NULL DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
